### ISSUE TITLE
绿动面板还有一个模式没能列出

### ISSUE THREAD

**Issue by wzguzi** [alkalixin/Hailin-Climate#1]
感谢更新。

绿动这个面板有5种模式，其中制热是出风的制热， 然后还有一个是地暖。另外有一个出风制热+地暖同时的模式。
制冷 operation: {"temp_cool":"c23.0","status":"1"}
制热 operation: {"temp_heat":"c23.0","status":"2"}
地暖 operation: {"fan_mod":"5","status":"7"}
通风 operation: {"fan_mod":"5","status":"5"}
制热+地暖 operation: {"fan_mod":"5","status":"8"}

抓包看到发送指令的时候，有一个status 8，不知道这种模式ha是否支持

**Comment by alkalixin** [comment]
```
# All activity disabled / Device is off/standby
HVAC_MODE_OFF = "off"
# Heating
HVAC_MODE_HEAT = "heat"
# Cooling
HVAC_MODE_COOL = "cool"
# The device supports heating/cooling to a range
HVAC_MODE_HEAT_COOL = "heat_cool"
# The temperature is set based on a schedule, learned behavior, AI or some
# other related mechanism. User is not able to adjust the temperature
HVAC_MODE_AUTO = "auto"
# Device is in Dry/Humidity mode
HVAC_MODE_DRY = "dry"
# Only the fan is on, not fan and another mode like cool
HVAC_MODE_FAN_ONLY = "fan_only"
HVAC_MODES = [
    HVAC_MODE_OFF,
    HVAC_MODE_HEAT,
    HVAC_MODE_COOL,
    HVAC_MODE_HEAT_COOL,
    HVAC_MODE_AUTO,
    HVAC_MODE_DRY,
    HVAC_MODE_FAN_ONLY,
]
```
climate可用的模式没有那么多。`HVAC_MODE_HEAT`被用来做地暖了，所以出风制热以及出风制热+地暖这两种情况没办法放到HA里面。

除非。。比如把`HVAC_MODE_HEAT_COOL`作为出风制热。把`HVAC_MODE_DRY`作为混合加热。
