### ISSUE TITLE
运行模式只有关闭一个选项

### ISSUE THREAD

**Issue by rickycm** [alkalixin/Hailin-Climate#2]
添加成功后，运行模式里面只有“关”，请问还需要配置哪里才能有其他操作选项？我用的是灵动空调温控面板，是不是这个面板的各个模式ID跟地暖的不太一样？

**Comment by alkalixin** [comment]
> 是不是这个面板的各个模式ID跟地暖的不太一样？

有可能。可以抓包看看devType是多少。

**Comment by rickycm** [comment]
support_fan_mode = device_json_object.get('dirty_fan_mod', True)  # 支持送风
support_heat_mode = device_json_object.get('dirty_heat_mode', True)  # 支持加热
support_cool_mode = device_json_object.get('dirty_temp_cool', True)  # 支持制冷

抓包发现response里面没有这三个状态，所以我直接把代码改成默认为True了，现在可以了。

**Comment by alkalixin** [comment]
可以把你抓包的数据脱敏发出来看一下吗。 我看看不同devType之间有什么区别。

**Comment by rickycm** [comment]
{
          "dgi_id": 235613,
          "devices_mac": "34EAXXXXXX",
          "group_id": 142730,
          "id": 10311291,
          "mac": "34EAXXXXXX",
          "dev_type": 9,
          "dis_dev_name": "餐厅空调",
          "req_interval": 30,
          "last_request_time": "2022-07-19 13:57:52",
          "device_json_object": "{\"dev_type\":9,\"dis_dev_name\":\"9023-FCU\",\"dis_dev_namecu_firmware_ver\":\"v1.8\",\"dis_temp\":\"c28.5\",\"encrypt\":\"a946139e3027147e6\",\"fan_mod\":0,\"keylock\":0,\"lowtemp_protect\":0,\"mac\":\"34EAE7FDA6DD\",\"mcu_firmware_ver\":\"v1.8\",\"power_memory\":2,\"req_interval\":30,\"save_energy\":false,\"status\":1,\"status_onoff\":0,\"temp_cool\":\"c25.0\",\"temp_cool_default_max\":\"c35.0\",\"temp_cool_default_min\":\"c05.0\",\"temp_cool_save_energy\":\"c26.0\",\"temp_heat\":\"c25.0\",\"temp_heat_default_max\":\"c35.0\",\"temp_heat_default_min\":\"c05.0\",\"temp_heat_save_energy\":\"c18.0\",\"temp_max\":\"c35.0\",\"temp_min\":\"c05.0\",\"wifi_firmware_ver\":\"1.00.24 (2021-01-22\"}",
          "is_enabled": 1,
          "created_at": "2022-06-25 18:32:41",
          "longitude": "",
          "latitude": "",
          "extend_json": "",
          "adcode": "",
          "mcu_program_code": "",
          "update_prior": 0,
          "last_update_queue_time": "",
          "last_update_value": 0,
          "utc_deviation": 0,
          "consecutive_update_times": 0,
          "upgrade_option": 0,
          "idc_setting": 0
        }

**Comment by rickycm** [comment]
现在还有一个问题是用空调面板打开后，Home Assistance里面没有更新状态。

**Comment by alkalixin** [comment]
> 现在还有一个问题是用空调面板打开后，Home Assistance里面没有更新状态。

不应该啊，初始化都能加载出来，更新状态是同一份逻辑啊。轮训时间结束后还是没有更新状态吗？ 日志有报错没？

**Comment by alkalixin** [comment]
[v1.4.1](https://github.com/alkalixin/Hailin-Climate/releases/tag/v1.4.1)

新版本已发布，可以通过配置support_XXX参数手动开启模式

**Comment by rickycm** [comment]
👍👍👍
